
#%RAML 0.8
title: Global Weather SOAP API converter 
version: 1.0
baseUri: http://localhost:8080/GlobalWeather
/GetCitiesByCountry:
    get:
        description: Find cities of this particular country. Key in Country Name as optional parameter to retrieve list of cities of this country.
        queryParameters:
          CountryName:
            displayName: CountryName
            type: string
            minLength: 4
            description: Find cities via this country key
            example: Australia
            required: false

/GetWeather:
    get:
        description: Find weather conditions of these countries or cities. Both Cities/Country parameters are optional. 
        queryParameters:
          CountryName:
            displayName: CountryName
            type: string
            minLength: 4
            description: Find Weather condition of this country 
            example: Australia
            required: false
          CityName:
            displayName: CityName
            type: string
            minLength: 4
            description: Find Weather condition of this city
            example: Bankstown Airport
            required: false